# Week2授業前課題3

# 1.この課題の目的
- 数式演算ライブラリのNumPyに慣れる。
- 機械学習に必須な微分について理解する。

# 【課題1】内積を手計算しよう

以下のベクトルA、Bの内積$\vec{ A } \cdot \vec{ B }$を求める。

$A=\begin{pmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9& \\ \end{pmatrix}$, $B=\begin{pmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1& \\ \end{pmatrix}$

$\vec{ A } \cdot \vec{ B }$の1行1列目の値$= (-1 \times 0) + (2 \times 0) + (3 \times 2) = 6$

$\vec{ A } \cdot \vec{ B }$の1行2列目の値$= (-1 \times 2) + (2 \times 2) + (3 \times 9) = 29$

$\vec{ A } \cdot \vec{ B }$の1行3列目の値$= (-1 \times 1) + (2 \times -8) + (3 \times -1) = -20$

$\vec{ A } \cdot \vec{ B }$の2行1列目の値$= (4 \times 0) + (-5 \times 0) + (6 \times 2) = 12$

$\vec{ A } \cdot \vec{ B }$の2行2列目の値$= (4 \times 2) + (-5 \times 2) + (6 \times 9) = 52$

$\vec{ A } \cdot \vec{ B }$の2行3列目の値$= (4 \times 1) + (-5 \times -8) + (6 \times -1) = 38$

$\vec{ A } \cdot \vec{ B }$の3行1列目の値$= (7 \times 0) + (8 \times 0) + (-9 \times 2) = -18$

$\vec{ A } \cdot \vec{ B }$の3行2列目の値$= (7 \times 2) + (8 \times 2) + (-9 \times 9) = -51$

$\vec{ A } \cdot \vec{ B }$の3行1列目の値$= (7 \times 1) + (8 \times -8) + (-9 \times -1) = -48$

上記より$\vec{ A } \cdot \vec{ B } = \begin{pmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48& \\ \end{pmatrix} $

# 【課題2】1次元配列の内積をfor文で計算しよう

In [1]:
import numpy as np

In [2]:
# 3行3列の行列Aを作成
A = np.array([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [3]:
# 3行3列の行列Bを作成
B = np.array([[0, 2, 1],[0, 2, -8],[2, 9, -1]])
B

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [4]:
# Aの1行目とBの1列目の内積を格納する為の変数ansを作成
ans = 0

# for分にてAの1行目とBの1列目の内積を計算
for i in range(3):
    ans = ans + A[0][i] * B[i][0]
ans

6

# 【課題3】多次元配列の内積をfor文で計算しよう

In [5]:
# 内積を格納するための3行3列の配列ans_arrayを作成
ans_arr = np.zeros((3, 3))
ans_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# for分を使用し行列Aと行列Bの内積を計算
for i1 in range(3):
    for i2 in range(3):
        for i3 in range(3):
            ans_arr[i1][i2] = ans_arr[i1][i2] + A[i1][i3] * B[i3][i2]
ans_arr

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 【課題4】内積をnp.dotで計算しよう

In [9]:
ans = np.dot(A, B)
ans

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【課題5】内積ができないときはどうするか

### 以下の行列Aと行列Bの内積が計算が出来ない理由

「行列Aの列数と行列Bの行数」及び「行列Aの行数と行列Bの列数」が異なる為である。

以下に詳細を記載する。

$A=\begin{pmatrix} -1 & 2 & 3 \\ 4 & -5 & 6\\ \end{pmatrix}$, $B=\begin{pmatrix} -9 & 8 & 7 \\ 6 & -5 & 4\\ \end{pmatrix}$

まず課題1で実施したように手計算で内積の値を求める。

$\vec{ A } \cdot \vec{ B }$の1行1列目の値$= (-1 \times -9) + (2 \times 6) + (3 \times ?) = ?$

$\vec{ A } \cdot \vec{ B }$の1行2列目の値$= (-1 \times 8) + (2 \times -5) + (3 \times ?) = ?$

$\vec{ A } \cdot \vec{ B }$の1行3列目の値$= (-1 \times 7) + (2 \times 4) + (3 \times ?) = ?$

$\vec{ A } \cdot \vec{ B }$の2行1列目の値$= (4 \times -9) + (-5 \times 6) + (6 \times ?) = ?$

$\vec{ A } \cdot \vec{ B }$の2行2列目の値$= (4 \times 8) + (-5 \times -5) + (6 \times ?) = ?$

$\vec{ A } \cdot \vec{ B }$の2行3列目の値$= (4 \times 7) + (-5 \times 4) + (6 \times ?) = ?$

上記の計算結果より、行列Bに3行目がない為、内積の計算に必要な値が足りないことがわかり、計算不可であることが確認できる。

### 行列Aと行列Bの内積値が計算できるようにする為の対応

上記にて内積が計算出来ない理由が、行列Bに3行目がないことが原因であることが判明した為、
行列Bを転置し3行2列の行列とすることで行列Aとの内積値が計算可能となる。

In [11]:
# 3行3列の行列Aを作成
A = np.array([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [12]:
# 2行3列の行列Bを作成
B = np.array([[9, 8, 7],[6, -5, 4]])
B

array([[ 9,  8,  7],
       [ 6, -5,  4]])

In [13]:
# 行列Bの転置行列Btを作成
Bt = B.T
Bt

array([[ 9,  6],
       [ 8, -5],
       [ 7,  4]])

In [14]:
# 行列Aと行列Btの内積値をnp.dot関数で計算し変数ansに格納
ans = np.dot(A, Bt)
ans

array([[ 28,  -4],
       [ 38,  73],
       [ 64, -34]])